@(#)PROGRAM:XCTestSwiftSupport  PROJECT:XCTest-19566
@__C
XCUIGestureVelocity
__C_Synthesized
XCTestError
NXCTestErrorCode
Code
NXCTestErrorCode
XCTIssue
XCTSkip
XCTest
UnwrappingOptional
XCTest
ObservedErrorContext
raise
dictionaryWithObjects:forKeys:count:
description
type
setType:
compactDescription
setCompactDescription:
detailedDescription
setDetailedDescription:
sourceCodeContext
setSourceCodeContext:
associatedError
setAssociatedError:
attachments
setAttachments:
addAttachment:
copy
mutableCopy
initWithType:compactDescription:detailedDescription:sourceCodeContext:associatedError:attachments:
initWithFilePath:lineNumber:
screenshotAttachmentWithName:lifetime:
message
initWithLocation:
initWithError:evaluatedExpression:message:sourceCodeContext:
initWithExpectedValue:evaluatedExpression:message:sourceCodeContext:
initWithException:evaluatedExpression:message:sourceCodeContext:
initWithExplanation:evaluatedExpression:message:sourceCodeContext:
addAsyncTeardownBlock:
init
setIssueMatcher:
setStrict:
setEnabled:
observeErrorsInBlock:
handleIssue:
reason
_installErrorObserver
_observeErrors
currentThread
threadDictionary
__swift_setObject:forKeyedSubscript:
initWithCallStackAddresses:location:
__swift_objectForKeyedSubscript:
callStackReturnAddresses
type
objc
exception
unknown
value
XCTest/XCTContext_SwiftExtensions.swift
XCTContext.runActivity(named:block:) failed because activities are disallowed in the current configuration.
v8@?0@?<v@?@"NSError">4
c8@?0@"XCTIssue"4
v4@?0
XCTest/XCTExpectedFailure_SwiftExtensions.swift
Fatal error
" was caught by XCTExpectFailure but there is currently no issue handler to determine whether it matches the expected failure. XCTExpectFailure can only be called with a throwing closure in contexts where an issue handler is set.
failed: caught error: "
XCTAssertNil failed: threw error "
XCTAssertNotNil failed: threw error "
XCTUnwrap failed: threw error "
XCTAssertTrue failed: threw error "
XCTAssertFalse failed: threw error "
XCTAssertEqual failed: threw error "
XCTAssertNotEqual failed: threw error "
XCTAssertIdentical
XCTAssertNotIdentical
XCTAssertGreaterThan failed: threw error "
XCTAssertGreaterThanOrEqual failed: threw error "
XCTAssertLessThan failed: threw error "
XCTAssertLessThanOrEqual failed: threw error "
XCTAssertThrowsError failed: throwing an unknown exception
XCTAssertThrowsError failed: throwing 
XCTAssertThrowsError failed: threw error "
XCTAssertThrowsError failed: did not throw an error
XCTAssertNoThrow failed: threw error "
 failed: threw error "
c8@0:4
@?8@0:4
@"XCTIssue"4@?0
com.apple.dt.xctest.swift-error-observation.observer-count
com.apple.dt.xctest.swift-error-observation.last-observed-error
_swift_willThrow
So7NSErrorC
$s10Foundation21_BridgedStoredNSErrorP
$sSY
$s10Foundation18_ErrorCodeProtocolP
So8NSNumberC
$ss21_ObjectiveCBridgeableP
ySo8XCTIssueCG
So8XCTIssueC
ySS_yptG
So21XCTSkippedTestContextC
ySSypG
SS_ypt
_pIeghHzo_
So7NSErrorCSgIeyBy_
_pSgIegg_
IeghH_
ytIeghHr_
_pIgrzo_
_pSg
ypSg
SDySSypG
_pIgzo_
So8NSThreadC
So7NSArrayC
$ss27ExpressibleByIntegerLiteralP
$ss25ExpressibleByFloatLiteralP
_nsError
rawValue
Code
RawValue
_ErrorType
_ObjectiveCType
_ObjectiveCType
underlyingIssue
value
skippedTestContext
errorCode
errorCode
errorUserInfo
error
callStackReturnAddresses
IntegerLiteralType
FloatLiteralType
@(#)PROGRAM:XCTestSwiftSupport  PROJECT:XCTest-19566
@__C
XCUIGestureVelocity
__C_Synthesized
XCTestError
NXCTestErrorCode
Code
NXCTestErrorCode
XCTIssue
XCTSkip
XCTest
UnwrappingOptional
XCTest
ObservedErrorContext
raise
dictionaryWithObjects:forKeys:count:
description
type
setType:
compactDescription
setCompactDescription:
detailedDescription
setDetailedDescription:
sourceCodeContext
setSourceCodeContext:
associatedError
setAssociatedError:
attachments
setAttachments:
addAttachment:
copy
mutableCopy
initWithType:compactDescription:detailedDescription:sourceCodeContext:associatedError:attachments:
initWithFilePath:lineNumber:
screenshotAttachmentWithName:lifetime:
message
initWithLocation:
initWithError:evaluatedExpression:message:sourceCodeContext:
initWithExpectedValue:evaluatedExpression:message:sourceCodeContext:
initWithException:evaluatedExpression:message:sourceCodeContext:
initWithExplanation:evaluatedExpression:message:sourceCodeContext:
addAsyncTeardownBlock:
init
setIssueMatcher:
setStrict:
setEnabled:
observeErrorsInBlock:
handleIssue:
reason
_installErrorObserver
_observeErrors
currentThread
threadDictionary
__swift_setObject:forKeyedSubscript:
initWithCallStackAddresses:location:
__swift_objectForKeyedSubscript:
callStackReturnAddresses
type
objc
exception
unknown
value
XCTest/XCTContext_SwiftExtensions.swift
XCTContext.runActivity(named:block:) failed because activities are disallowed in the current configuration.
v16@?0@?<v@?@"NSError">8
B16@?0@"XCTIssue"8
v8@?0
XCTest/XCTExpectedFailure_SwiftExtensions.swift
Fatal error
" was caught by XCTExpectFailure but there is currently no issue handler to determine whether it matches the expected failure. XCTExpectFailure can only be called with a throwing closure in contexts where an issue handler is set.
failed: caught error: "
XCTAssertNil failed: threw error "
XCTAssertNotNil failed: threw error "
XCTUnwrap failed: threw error "
XCTAssertTrue failed: threw error "
XCTAssertFalse failed: threw error "
XCTAssertEqual failed: threw error "
XCTAssertNotEqual failed: threw error "
XCTAssertIdentical
XCTAssertNotIdentical
XCTAssertGreaterThan failed: threw error "
XCTAssertGreaterThanOrEqual failed: threw error "
XCTAssertLessThan failed: threw error "
XCTAssertLessThanOrEqual failed: threw error "
XCTAssertThrowsError failed: throwing an unknown exception
XCTAssertThrowsError failed: throwing 
XCTAssertThrowsError failed: threw error "
XCTAssertThrowsError failed: did not throw an error
XCTAssertNoThrow failed: threw error "
 failed: threw error "
B16@0:8
@?16@0:8
@"XCTIssue"8@?0
com.apple.dt.xctest.swift-error-observation.last-observed-error
com.apple.dt.xctest.swift-error-observation.observer-count
_swift_willThrow
So7NSErrorC
$s10Foundation21_BridgedStoredNSErrorP
$sSY
$s10Foundation18_ErrorCodeProtocolP
So8NSNumberC
$ss21_ObjectiveCBridgeableP
ySo8XCTIssueCG
So8XCTIssueC
ySS_yptG
So21XCTSkippedTestContextC
ySSypG
SS_ypt
_pIeghHzo_
So7NSErrorCSgIeyBy_
_pSgIegg_
IeghH_
ytIeghHr_
_pIgrzo_
_pSg
ypSg
SDySSypG
_pIgzo_
So8NSThreadC
So7NSArrayC
$ss27ExpressibleByIntegerLiteralP
$ss25ExpressibleByFloatLiteralP
_nsError
rawValue
Code
RawValue
_ErrorType
_ObjectiveCType
_ObjectiveCType
underlyingIssue
value
skippedTestContext
errorCode
errorCode
errorUserInfo
error
callStackReturnAddresses
IntegerLiteralType
FloatLiteralType
@(#)PROGRAM:XCTestSwiftSupport  PROJECT:XCTest-19566
@__C
XCUIGestureVelocity
__C_Synthesized
XCTestError
NXCTestErrorCode
Code
NXCTestErrorCode
XCTIssue
XCTSkip
XCTest
UnwrappingOptional
XCTest
ObservedErrorContext
raise
dictionaryWithObjects:forKeys:count:
description
type
setType:
compactDescription
setCompactDescription:
detailedDescription
setDetailedDescription:
sourceCodeContext
setSourceCodeContext:
associatedError
setAssociatedError:
attachments
setAttachments:
addAttachment:
copy
mutableCopy
initWithType:compactDescription:detailedDescription:sourceCodeContext:associatedError:attachments:
initWithFilePath:lineNumber:
screenshotAttachmentWithName:lifetime:
message
initWithLocation:
initWithError:evaluatedExpression:message:sourceCodeContext:
initWithExpectedValue:evaluatedExpression:message:sourceCodeContext:
initWithException:evaluatedExpression:message:sourceCodeContext:
initWithExplanation:evaluatedExpression:message:sourceCodeContext:
addAsyncTeardownBlock:
init
setIssueMatcher:
setStrict:
setEnabled:
observeErrorsInBlock:
handleIssue:
reason
_installErrorObserver
_observeErrors
currentThread
threadDictionary
__swift_setObject:forKeyedSubscript:
initWithCallStackAddresses:location:
__swift_objectForKeyedSubscript:
callStackReturnAddresses
type
objc
exception
unknown
value
XCTest/XCTContext_SwiftExtensions.swift
XCTContext.runActivity(named:block:) failed because activities are disallowed in the current configuration.
v16@?0@?<v@?@"NSError">8
B16@?0@"XCTIssue"8
v8@?0
XCTest/XCTExpectedFailure_SwiftExtensions.swift
Fatal error
" was caught by XCTExpectFailure but there is currently no issue handler to determine whether it matches the expected failure. XCTExpectFailure can only be called with a throwing closure in contexts where an issue handler is set.
failed: caught error: "
XCTAssertNil failed: threw error "
XCTAssertNotNil failed: threw error "
XCTUnwrap failed: threw error "
XCTAssertTrue failed: threw error "
XCTAssertFalse failed: threw error "
XCTAssertEqual failed: threw error "
XCTAssertNotEqual failed: threw error "
XCTAssertIdentical
XCTAssertNotIdentical
XCTAssertGreaterThan failed: threw error "
XCTAssertGreaterThanOrEqual failed: threw error "
XCTAssertLessThan failed: threw error "
XCTAssertLessThanOrEqual failed: threw error "
XCTAssertThrowsError failed: throwing an unknown exception
XCTAssertThrowsError failed: throwing 
XCTAssertThrowsError failed: threw error "
XCTAssertThrowsError failed: did not throw an error
XCTAssertNoThrow failed: threw error "
 failed: threw error "
B16@0:8
@?16@0:8
@"XCTIssue"8@?0
com.apple.dt.xctest.swift-error-observation.last-observed-error
com.apple.dt.xctest.swift-error-observation.observer-count
_swift_willThrow
So7NSErrorC
$s10Foundation21_BridgedStoredNSErrorP
$sSY
$s10Foundation18_ErrorCodeProtocolP
So8NSNumberC
$ss21_ObjectiveCBridgeableP
ySo8XCTIssueCG
So8XCTIssueC
ySS_yptG
So21XCTSkippedTestContextC
ySSypG
SS_ypt
_pIeghHzo_
So7NSErrorCSgIeyBy_
_pSgIegg_
IeghH_
ytIeghHr_
_pIgrzo_
_pSg
ypSg
SDySSypG
_pIgzo_
So8NSThreadC
So7NSArrayC
$ss27ExpressibleByIntegerLiteralP
$ss25ExpressibleByFloatLiteralP
_nsError
rawValue
Code
RawValue
_ErrorType
_ObjectiveCType
_ObjectiveCType
underlyingIssue
value
skippedTestContext
errorCode
errorCode
errorUserInfo
error
callStackReturnAddresses
IntegerLiteralType
FloatLiteralType
